### PR TITLE
CMake: Fix macOS GCC compilation: Link PNG::PNG

### PR DESCRIPTION
**Pull request by zbeekman**
- On macOS builds with brewed gcc8 and gcc9 were failing to link `libpng`
    - I guess Apple's clang/cc have this stored away in Xcode paths somewhere
  - To find my brewed `libpng` correctly one cannot simply pass `png` to
    `target_link_libraries()`
  - Since minimum allowed CMake is 3.9, take advantage of transitive linked
    target property propagation and link to the exported target, `PNG::PNG`
    defined by the intrinsic `FindPNG.cmake` CMake module

Note: By using the `PNG::PNG` exported target include search paths, additional defines and any special compiler flags are propagated correctly (assuming there are no bugs in the intrinsic CMake module, `FindPNG.cmake`).

@kellykochanski @r-barnes a few questions:

- Who/what is using `zlib`?
  - If you just need gzip you can use [`FindUnixCommands.cmake`](https://cmake.org/cmake/help/v3.9/module/FindUnixCommands.html)
- Is there a reason not to use CMake's [`zlib` support](https://cmake.org/cmake/help/v3.9/module/FindZLIB.html)?
  - i.e., link against `ZLIB::ZLIB` for targets requiring it
- Why is `pthread` being linked for `rescal` without finding it/verifying its presence first?
  - You can use [FindThreads.cmake](https://cmake.org/cmake/help/v3.9/module/FindThreads.html) with `Threads::Threads` and control preferring pthreads etc. with the control variables
- Is pthreads still even required?

I can help update CMake a bit more based on your responses here. Using exported targets should improve the robustness of the build system.

### CODE REVIEW

**Comment by kellykochanski** [comment]
@egreen77 could you and/or @r-barnes take a look at another build/dependency issue?

**Comment by r-barnes** [comment]
@zbeekman: Good catch. `zlib` was required for libpng, but is no longer
necessary. We can cut that.

`PNG::PNG` is the better target to link against, thank you for pointing
that out.

I'm not sure what pthreads is needed for. I can check that out this
evening. Does @kellykochanski know?

**Comment by egreen77** [comment]
From what I recall, the program uses pthreads to handle control signals and file IO. It may also have some very limited task-based parallelism that relies on pthreads.

**Comment by r-barnes** [comment]
@zbeekman : I've tested your suggestions and they seem to work fine, so I've pushed to your PR branch.

I'll separately experiment with whether pthreads can be dropped entirely, it doesn't look that useful.

**Comment by zbeekman** [comment]
@r-barnes: FYI I pushed a small commit to tweak your handling for pthreads. Now the build will attempt to continue if pthreads is not found.

I don't love that `target_link_libraries()` is being passed `m` which implies that it will then add the linker flag `-lm` (so long as no one has defined a library target named `m`) unconditionally because it's not very future proof if compilers ever decide to drop support for `-lm` or packaging a separate `libm` but all the CMake work arounds I've seen for this appear to be clunky or unreliable.

So, IMO, this is ready to merge, assuming someone has tested with Intel & GCC on linux. (I'll do so later this weekend if no one gets the chance before then.)

**Comment by r-barnes** [comment]
@zbeekman: The build will fail if it can't link pthreads, so maybe it's better just to set the `find_package` on threads to required?

**Comment by zbeekman** [comment]
@r-barnes: If you confirmed you need pthreads to build, then yes, remove the `if` statement logic and add `REQUIRED` to `find_package(...)`... Actually I'll just do it quickly for you.

**Comment by zbeekman** [comment]
This is good to go AFIACT. I tested on MacOS w/ GCC and native apple clang.

**Comment by r-barnes** [comment]
Builds on Linux for me.

**Pull request merged**
