### PR TITLE
Build system fixes

### LINKED ISSUE #26: JOSS Review (@rgmyr): ZLIB not found by CMake
Following the installation notes as written resulted in a CMake error:
```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  lib/libpng-1.6.37/CMakeLists.txt:42 (find_package)

-- Configuring incomplete, errors occurred!
```
I see that `zlib-1.2.11` is included in `rescal-snow/lib/`, but it doesn't seem to be properly linked by default, at least on my machine. The installation proceeded without that error after manually installing `zlib1g-dev`:
```
$ sudo apt-get install zlib1g-dev
```

### PR DESCRIPTION
**Pull request by egreen77**
Fixes #26 and #27

### CODE REVIEW

**Comment by egreen77** [comment]
Added a small patch that should fix build errors when CMAKE_SOURCE_DIR != CMAKE_BINARY_DIR (out-of-tree builds).

**Comment by r-barnes** [comment]
@egreen77 : This is working on my end. I've pushed a commit that drops `HOMEPAGE_URL`, since that restricts the version of cmake needed (our bad). What's `ExternalProject` being used for here?

**Comment by egreen77** [comment]
That line can be dropped. I was going to convert the subdirectories into external projects before I noticed that the issue could be fixed more simply.

**Comment by r-barnes** [comment]
@egreen77 : Could you split out fixing the `fread` return checks into a separate PR? Unless you object, I think we might drop our internal copies of zlib and png in favour of using cmake's `find_package` utility.

**Comment by egreen77** [comment]
I've split the PR. The bundled copies of the libraries were originally added so things would compile on specific machines here at LLNL. They can be safely removed if compatibility with a more restricted environment is no longer needed.

**Pull request closed without merging**
