### PR TITLE
Fix up testing

### PR DESCRIPTION
**Pull request by r-barnes**

### CODE REVIEW

**Comment by r-barnes** [comment]
This PR, which others can edit, is for improving testing. It starts from @kellykochanski 's script, but automates the testing procedure by exiting with a non-zero status if errors occur and including outputs from simulation(s) which are known to be working.

**Comment by r-barnes** [comment]
Primary difference is including an output from snow cone and having the computer automatically compare against this. Results should be identical unless random seed of floating-point math vary somehow. It may be better to include a non-PNG output, but I'm not sure which one is best.

Note that the visual test would not work unless the user already knew what the result should look like.

**Comment by kellykochanski** [comment]
@r-barnes The random seed of the stochastic cellular automaton varies by default.

**Comment by r-barnes** [comment]
snow cone seems to run deterministically for me. I couldn't get `viz_example_test.py` to reproduce, though, so I've commented that out for now.

**Comment by kellykochanski** [comment]
Since the test was aimed to cover the once-deprecated code in the visualization example, I've restored that half of the test I wrote. 

The random seed is now fixed. I'm surprised snow_cone ran deterministically for you...

**Comment by r-barnes** [comment]
`param_space_exploration.py` can be tested deterministically by the machine, so I've pulled this out of `test-utilities.sh`.

**Pull request merged**
