### PR TITLE
Ib/doc fixes

### PR DESCRIPTION
**Pull request by zbeekman**
Mostly broken link fixes

### CODE REVIEW

**Comment by zbeekman** [comment]
@kellykochanski I think this is ready to merge.

**Comment by kellykochanski** [comment]
@zbeekman Does trailing whitespace negatively affect markdown documents?

**Comment by zbeekman** [comment]
@kellykochanski 

> Does trailing whitespace negatively affect markdown documents?

Sorry, no it does not, but if I'm editing it I am almost always feel compelled to remove it. I should really make sure I put it in stand-alone commits, however, sorry!

And in general, a reason why it bothers me is that consistent whitespace usage by the team makes it easier to understand diffs. Sometimes peoples editors have default settings to trim trailing space, or use tabs instead of spaces for indentation, etc. (Each one also takes up an additional byte 😝, not really a good reason but... 🤷‍♂)

On a side note, to encourage consistency in the project, I highly recommend [EditorConfig](https://editorconfig.org). Many editors support it out of the box, and others have relatively easy plugins you can install.

**Comment by r-barnes** [comment]
@zbeekman: clang-format (https://github.com/barisione/clang-format-hooks)
as a precommit hook can also be an effective way of enforcing, and
automatically correcting, style.

**Comment by zbeekman** [comment]
Both have pros and cons. Clang format knows about the AST which makes it better for programming languages it supports. Editor config is general and provides as-you-type feedback and/or correction.

**Pull request merged**
