### PR TITLE
Use find_package instead of including png and zlib ourselves

### PR DESCRIPTION
**Pull request by r-barnes**
Potential PR to simplify build by relying on cmake to locate dependencies.

### CODE REVIEW

**Comment by r-barnes** [comment]
@egreen77 : This incorporates the PR you made for `fread`. If you have time, could you see if it works for you?

**Comment by kellykochanski** [comment]
This compiles smoothly, but I'm now getting a new bug at run-time:
```bash
$ ./snow_cone.run
PAR_FILE=snow_cone.par
OMP_NUM_THREADS=1
Read error
rescal-snow/src/format.c (261)
```
Triggered by the following check in `format.c`:
```C
    if ((int32_t)fread(buf, csp_cell_size, csp_H * csp_L, fp) != (csp_cell_size * csp_H * csp_L)) {
      ErrPrintf("Read error\n");
      exit(-1);
    }
```

**Comment by r-barnes** [comment]
[fread](http://www.cplusplus.com/reference/cstdio/fread/) checks the number of elements, not the number of bytes, so we switch:
```
if ((int32_t)fread(buf, csp_cell_size, csp_H * csp_L, fp) != (csp_cell_size * csp_H * csp_L))
```
to
```
if ((int32_t)fread(buf, csp_cell_size, csp_H * csp_L, fp) != (csp_H * csp_L))
```

**Comment by kellykochanski** [comment]
This no longer compiles (gcc 8.3.0):
```bash
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/bin2png.dir/build.make:76: CMakeFiles/bin2png.dir/src/lgca.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 77%] Building C object CMakeFiles/rescal.dir/src/space.c.o
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/rescal.dir/build.make:76: CMakeFiles/rescal.dir/src/lgca.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 79%] Building C object CMakeFiles/csp2png.dir/src/transitions.c.o
[ 81%] Building C object CMakeFiles/csp2png.dir/src/view.c.o
[ 82%] Building C object CMakeFiles/csp2png.dir/src/csp2png.c.o
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/csp2png.dir/build.make:76: CMakeFiles/csp2png.dir/src/lgca.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/bin2png.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/csp2png.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/rescal.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by r-barnes** [comment]
Try fixing the sign by casting fread to int32_t

**Comment by kellykochanski** [comment]
Compiles + runs test cases.

**Pull request merged**
